abort if no tag found

diff --git a/.github/workflows/version-bumper-chrome-runner.yaml b/.github/workflows/version-bumper-chrome-runner.yaml
--- a/.github/workflows/version-bumper-chrome-runner.yaml
+++ b/.github/workflows/version-bumper-chrome-runner.yaml
@@ -1,4 +1,4 @@
-name: Check for new docker tag of chrome runner base image and bump version of possible
+name: "[chrome-runner] Check for new base image tags and bump"
 
 on:
   schedule:
@@ -38,7 +38,14 @@ jobs:
     - name: Check latest tag for aarch64
       id: latest_aarch64
       run: |
-        LATEST_TAG=$(curl -s https://ghcr.io/v2/zenika/alpine-chrome/tags/list | jq -r '.tags[]' | sort -V | tail -n 1)
+        LATEST_TAG=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" https://ghcr.io/v2/zenika/alpine-chrome/tags/list | jq -r '.tags[]' | sort -V | tail -n 1)
+
+        # Check if the latest tag is empty
+        if [ -z "$LATEST_TAG" ]; then
+          echo "Error: No tags found or latest tag is empty. Aborting."
+          exit 1
+        fi
+        
         echo "Latest tag: $LATEST_TAG"
         echo "::set-output name=latest_tag::$LATEST_TAG"
 
